# Generated by Django 3.1.5 on 2021-01-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='garder',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
