# Generated by Django 3.1.5 on 2021-01-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='categ',
            field=models.ManyToManyField(to='erp.Categoria'),
        ),
    ]
